## Formatting production data

In [34]:
# Load your new, clean production data
prod_df = pd.read_csv('D:/Work/Coding/SIH 2025/agricultural-ai-platform/data/fertilizer_model/crop_production.csv')

# --- Data Cleaning ---
# The column names might have extra spaces. Let's fix them.
prod_df.columns = [col.strip() for col in prod_df.columns]

# Standardize names for merging
prod_df['State'] = prod_df['State'].apply(standardize_name)
prod_df['District'] = prod_df['District'].apply(standardize_name)
prod_df['Crop'] = prod_df['Crop'].apply(standardize_name)

# Ensure Year is a clean integer
prod_df['Year'] = pd.to_numeric(prod_df['Year'], errors='coerce').astype('Int64')

# Handle potential missing values
prod_df.dropna(subset=['Yield_Tonnes_per_Hectare'], inplace=True)


print("\nCleaned Production Data:")
print(prod_df.head())

Cleaned Production Data:
                         State  District  Year          Crop  Area_Hectare  \
0  andaman and nicobar islands  nicobars  2000        banana         176.0
1  andaman and nicobar islands  nicobars  2000     cashewnut         720.0
2  andaman and nicobar islands  nicobars  2000        ginger          36.0
3  andaman and nicobar islands  nicobars  2000     sugarcane           1.0
4  andaman and nicobar islands  nicobars  2000  sweet_potato           5.0

   Production_Tonnes  Yield_Tonnes_per_Hectare
0              641.0                      3.64
1              165.0                      0.23
2              100.0                      2.78
3                2.0                      2.00
4               15.0                      3.00

In [36]:
prod_df.columns

Index(['State', 'District', 'Year', 'Crop', 'Area_Hectare',
       'Production_Tonnes', 'Yield_Tonnes_per_Hectare'],
      dtype='object')

In [38]:
import pandas as pd

# Define the helper function for standardizing names
def standardize_name(name):
    if isinstance(name, str):
        return name.strip().lower()
    return name

# --- Step 1: Load and Clean the Production Data (The Correct Way) ---

# Load your production data
prod_df = pd.read_csv('D:/Work/Coding/SIH 2025/agricultural-ai-platform/data/fertilizer_model/crop_production.csv')

# The column names might have leading/trailing spaces. Let's fix them.
prod_df.columns = [col.strip() for col in prod_df.columns]

# Standardize the names in the data for accurate merging
prod_df['State'] = prod_df['State'].apply(standardize_name)
prod_df['District'] = prod_df['District'].apply(standardize_name)
prod_df['Crop'] = prod_df['Crop'].apply(standardize_name)

# Ensure 'Year' is a clean integer (e.g., convert 2000.0 to 2000)
prod_df['Year'] = pd.to_numeric(prod_df['Year'], errors='coerce').astype('Int64')

# Drop any rows where the target variable 'Yield_Tonnes_per_Hectare' is missing
prod_df.dropna(subset=['Yield_Tonnes_per_Hectare'], inplace=True)


# --- That's it! Your production data is ready. ---
print("----------- Cleaned Production Data (Error Fixed) -----------")
print(prod_df.head())
print("\n----------- Info about the cleaned dataframe -----------")
prod_df.info()

# You can now proceed directly to the merge steps with this 'prod_df'
# For example:
# master_df = pd.merge(prod_df, soil_df, on=['State', 'District'], how='left')

----------- Cleaned Production Data (Error Fixed) -----------
                         State  District  Year          Crop  Area_Hectare  \
0  andaman and nicobar islands  nicobars  2000        banana         176.0
1  andaman and nicobar islands  nicobars  2000     cashewnut         720.0
2  andaman and nicobar islands  nicobars  2000        ginger          36.0
3  andaman and nicobar islands  nicobars  2000     sugarcane           1.0
4  andaman and nicobar islands  nicobars  2000  sweet_potato           5.0

   Production_Tonnes  Yield_Tonnes_per_Hectare
0              641.0                      3.64
1              165.0                      0.23
2              100.0                      2.78
3                2.0                      2.00
4               15.0                      3.00

----------- Info about the cleaned dataframe -----------
<class 'pandas.core.frame.DataFrame'>
Index: 34785 entries, 0 to 34785
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   State                     34785 non-null  object
 1   District                  34785 non-null  object
 2   Year                      34785 non-null  Int64
 3   Crop                      34785 non-null  object
 4   Area_Hectare              34736 non-null  float64
 5   Production_Tonnes         34073 non-null  float64
 6   Yield_Tonnes_per_Hectare  34785 non-null  float64
dtypes: Int64(1), float64(3), object(3)
memory usage: 2.2+ MB

## Soil data + Merge

In [28]:
master_df = prod_df
import pandas as pd
# Load soil data
soil_df = pd.read_csv('D:/Work/Coding/SIH 2025/agricultural-ai-platform/data/fertilizer_model/district_soil_mapping.csv')
# Load and clean soil data
soil_df['state'] = soil_df['state'].apply(standardize_name)
soil_df['district'] = soil_df['district'].apply(standardize_name)
soil_df = soil_df.rename(columns={'state': 'State', 'district': 'District'})

# Merge with soil data
master_df = pd.merge(master_df, soil_df, on=['State', 'District'], how='left')
master_df.head(10)

,State,District,Year,Crop,Area_Hectare,Production_Tonnes,Yield_Tonnes_per_Hectare,primary_soil_type,secondary_soil_type,ph_level,...,cation_exchange_capacity,bulk_density,infiltration_rate_mm_per_hour,available_water_capacity_mm,micronutrient_status,soil_temperature_celsius,major_constraints,land_use_pattern,irrigation_potential,groundwater_depth_meters
0,andaman and nicobar islands,nicobars,2000,banana,176.0,641.0,3.64,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,andaman and nicobar islands,nicobars,2000,cashewnut,720.0,165.0,0.23,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,andaman and nicobar islands,nicobars,2000,ginger,36.0,100.0,2.78,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,andaman and nicobar islands,nicobars,2000,sugarcane,1.0,2.0,2.00,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,andaman and nicobar islands,nicobars,2000,sweet_potato,5.0,15.0,3.00,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,andaman and nicobar islands,nicobars,2000,tapioca,40.0,169.0,4.23,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,andaman and nicobar islands,nicobars,2001,cashewnut,719.0,192.0,0.27,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,andaman and nicobar islands,nicobars,2001,ginger,46.0,100.0,2.17,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,andaman and nicobar islands,nicobars,2001,sugarcane,1.0,1.0,1.00,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,andaman and nicobar islands,nicobars,2001,sweet_potato,11.0,33.0,3.00,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Fixing the merge Problem

In [14]:
import pandas as pd
# Load soil data
soil_df = pd.read_csv('D:/Work/Coding/SIH 2025/agricultural-ai-platform/data/fertilizer_model/district_soil_mapping.csv')
# Load and clean soil data
soil_df['state'] = soil_df['state'].apply(standardize_name)
soil_df['district'] = soil_df['district'].apply(standardize_name)
soil_df = soil_df.rename(columns={'state': 'State', 'district': 'District'})

# --- The Grand Merge ---
# Start with the production data as the base
master_df = prod_df

# Merge with soil data
master_df = pd.merge(master_df, soil_df, on=['State', 'District'], how='left')

# Merge with aggregated rainfall data
master_df = pd.merge(master_df, yearly_rainfall_df, on=['State', 'District', 'Year'], how='left')

master_df = pd.merge(master_df, yearly_rainfall_df, on=['State', 'District', 'Year'], how='left')
master_df = pd.merge(master_df, yearly_soil_moisture_df, on=['State', 'District', 'Year'], how='left')

# (You would also merge your yearly_soil_moisture_df and temperature data here)

# --- Final Checks ---
print("\n--- Final Master Dataset ---")
print(master_df.head())
print("\nMaster Dataset Info:")
master_df.info()

--- Final Master Dataset ---
                         State  District  Year          Crop  Area_Hectare  \
0  andaman and nicobar islands  nicobars  2000        banana         176.0
1  andaman and nicobar islands  nicobars  2000     cashewnut         720.0
2  andaman and nicobar islands  nicobars  2000        ginger          36.0
3  andaman and nicobar islands  nicobars  2000     sugarcane           1.0
4  andaman and nicobar islands  nicobars  2000  sweet_potato           5.0

   Production_Tonnes  Yield_Tonnes_per_Hectare primary_soil_type  \
0              641.0                      3.64               NaN
1              165.0                      0.23               NaN
2              100.0                      2.78               NaN
3                2.0                      2.00               NaN
4               15.0                      3.00               NaN

  secondary_soil_type  ph_level  ...  rabi_rainfall_x summer_rainfall_x  \
0                 NaN       NaN  ...              NaN               NaN
1                 NaN       NaN  ...              NaN               NaN
2                 NaN       NaN  ...              NaN               NaN
3                 NaN       NaN  ...              NaN               NaN
4                 NaN       NaN  ...              NaN               NaN

  total_annual_rainfall_y kharif_rainfall_y  rabi_rainfall_y  \
0                     NaN               NaN              NaN
1                     NaN               NaN              NaN
2                     NaN               NaN              NaN
3                     NaN               NaN              NaN
4                     NaN               NaN              NaN

  summer_rainfall_y avg_annual_soil_moisture avg_kharif_moisture  \
0               NaN                      NaN                 NaN
1               NaN                      NaN                 NaN
2               NaN                      NaN                 NaN
3               NaN                      NaN                 NaN
4               NaN                      NaN                 NaN

  avg_rabi_moisture  avg_summer_moisture
0               NaN                  NaN
1               NaN                  NaN
2               NaN                  NaN
3               NaN                  NaN
4               NaN                  NaN

[5 rows x 44 columns]

Master Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34785 entries, 0 to 34784
Data columns (total 44 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   State                           34785 non-null  object
 1   District                        34785 non-null  object
 2   Year                            34785 non-null  Int64
 3   Crop                            34785 non-null  object
 4   Area_Hectare                    34736 non-null  float64
 5   Production_Tonnes               34073 non-null  float64
 6   Yield_Tonnes_per_Hectare        34785 non-null  float64
 7   primary_soil_type               30231 non-null  object
 8   secondary_soil_type             30231 non-null  object
 9   ph_level                        30231 non-null  float64
 10  organic_matter_percent          30231 non-null  float64
 11  nitrogen_level                  30231 non-null  object
 12  phosphorus_level                30231 non-null  object
 13  potassium_level                 30231 non-null  object
 14  water_holding_capacity_percent  30231 non-null  float64
 15  drainage                        30231 non-null  object
 16  erosion_risk                    30231 non-null  object
 17  salinity_level                  30231 non-null  object
 18  texture                         30231 non-null  object
 19  depth_cm                        30231 non-null  float64
 20  elevation_meters                30231 non-null  float64
 21  slope_percent                   30231 non-null  float64
 22  cation_exchange_capacity        30231 non-null  float64
 23  bulk_density                    30231 non-null  float64
 24  infiltration_rate_mm_per_hour   30231 non-null  float64
 25  available_water_capacity_mm     30231 non-null  float64
 26  micronutrient_status            30231 non-null  object
 27  soil_temperature_celsius        30231 non-null  float64
 28  major_constraints               30231 non-null  object
 29  land_use_pattern                30231 non-null  object
 30  irrigation_potential            30231 non-null  object
 31  groundwater_depth_meters        30231 non-null  float64
 32  total_annual_rainfall_x         1157 non-null   float64
 33  kharif_rainfall_x               1157 non-null   float64
 34  rabi_rainfall_x                 1157 non-null   float64
 35  summer_rainfall_x               1157 non-null   float64
 36  total_annual_rainfall_y         1157 non-null   float64
 37  kharif_rainfall_y               1157 non-null   float64
 38  rabi_rainfall_y                 1157 non-null   float64
 39  summer_rainfall_y               1157 non-null   float64
 40  avg_annual_soil_moisture        1157 non-null   float64
 41  avg_kharif_moisture             1157 non-null   float64
 42  avg_rabi_moisture               1157 non-null   float64
 43  avg_summer_moisture             1157 non-null   float64
dtypes: Int64(1), float64(27), object(16)
memory usage: 11.7+ MB

In [26]:
soil_df.head(10)

,State,District,primary_soil_type,secondary_soil_type,ph_level,organic_matter_percent,nitrogen_level,phosphorus_level,potassium_level,water_holding_capacity_percent,...,cation_exchange_capacity,bulk_density,infiltration_rate_mm_per_hour,available_water_capacity_mm,micronutrient_status,soil_temperature_celsius,major_constraints,land_use_pattern,irrigation_potential,groundwater_depth_meters
0,andhra pradesh,alluri sitharama raju,alluvial,laterite,7.7,3.4,medium,low,low,17.3,...,34.1,1.25,10.7,102.0,sufficient,25.5,salinity,agriculture,high,27.2
1,andhra pradesh,anakapalli,alluvial,black_cotton,6.6,4.4,low,low,medium,30.3,...,7.3,1.76,48.4,177.0,deficient,15.3,waterlogging,urban,low,34.8
2,andhra pradesh,anantapuramu,laterite,red_yellow,6.2,1.2,medium,low,high,32.0,...,18.8,1.75,36.9,119.2,sufficient,18.9,none,barren,high,15.0
3,andhra pradesh,annamayya,red_yellow,laterite,6.0,1.6,medium,low,high,18.0,...,12.0,1.60,39.9,152.7,sufficient,22.2,none,urban,low,42.8
4,andhra pradesh,bapatla,laterite,black_cotton,5.1,2.0,medium,medium,medium,26.0,...,30.3,1.27,14.3,84.9,adequate,23.6,waterlogging,urban,high,11.7
5,andhra pradesh,chittoor,laterite,alluvial,5.7,2.8,medium,low,medium,36.6,...,33.3,1.54,43.8,176.4,sufficient,32.7,waterlogging,urban,high,17.3
6,andhra pradesh,dr. b.r. ambedkar konaseema,red_yellow,red_yellow,5.8,2.2,high,high,low,35.4,...,38.0,1.33,26.9,164.4,deficient,16.3,waterlogging,urban,medium,35.4
7,andhra pradesh,east godavari,alluvial,red_yellow,6.7,4.5,low,high,medium,16.3,...,20.7,1.49,30.4,89.7,adequate,19.8,alkalinity,barren,medium,32.4
8,andhra pradesh,eluru,alluvial,alluvial,6.6,3.8,medium,low,low,38.6,...,11.1,1.58,20.6,192.4,deficient,28.5,none,agriculture,medium,46.4
9,andhra pradesh,guntur,black_cotton,black_cotton,7.4,3.1,high,medium,medium,24.7,...,16.9,1.34,36.8,187.7,sufficient,30.6,salinity,forest,high,9.8

In [24]:
master_df.isnull().sum()

State                                 0
District                              0
Year                                  0
Crop                                  0
Area_Hectare                         49
Production_Tonnes                   712
Yield_Tonnes_per_Hectare              0
primary_soil_type                  4554
secondary_soil_type                4554
ph_level                           4554
organic_matter_percent             4554
nitrogen_level                     4554
phosphorus_level                   4554
potassium_level                    4554
water_holding_capacity_percent     4554
drainage                           4554
erosion_risk                       4554
salinity_level                     4554
texture                            4554
depth_cm                           4554
elevation_meters                   4554
slope_percent                      4554
cation_exchange_capacity           4554
bulk_density                       4554
infiltration_rate_mm_per_hour      4554
available_water_capacity_mm        4554
micronutrient_status               4554
soil_temperature_celsius           4554
major_constraints                  4554
land_use_pattern                   4554
irrigation_potential               4554
groundwater_depth_meters           4554
total_annual_rainfall_x           33628
kharif_rainfall_x                 33628
rabi_rainfall_x                   33628
summer_rainfall_x                 33628
total_annual_rainfall_y           33628
kharif_rainfall_y                 33628
rabi_rainfall_y                   33628
summer_rainfall_y                 33628
avg_annual_soil_moisture          33628
avg_kharif_moisture               33628
avg_rabi_moisture                 33628
avg_summer_moisture               33628
dtype: int64

In [25]:
# Save master_df as CSV in the data folder
import os

# Define the output path
output_path = 'D:/Work/Coding/SIH 2025/agricultural-ai-platform/data/master_df_combined.csv'

# Save the master_df to CSV
master_df.to_csv(output_path, index=False)

print(f"✅ Master dataframe saved successfully to: {output_path}")
print(f"📊 Shape: {master_df.shape}")
print(f"📁 File size: {os.path.getsize(output_path) / (1024*1024):.2f} MB")

# Display first few rows of the saved data
print("\n📋 First 5 rows of saved master_df:")
print(master_df.head())

✅ Master dataframe saved successfully to: D:/Work/Coding/SIH 2025/agricultural-ai-platform/data/master_df_combined.csv
📊 Shape: (34785, 44)
📁 File size: 7.03 MB

📋 First 5 rows of saved master_df:
                         State  District  Year          Crop  Area_Hectare  \
0  andaman and nicobar islands  nicobars  2000        banana         176.0
1  andaman and nicobar islands  nicobars  2000     cashewnut         720.0
2  andaman and nicobar islands  nicobars  2000        ginger          36.0
3  andaman and nicobar islands  nicobars  2000     sugarcane           1.0
4  andaman and nicobar islands  nicobars  2000  sweet_potato           5.0

   Production_Tonnes  Yield_Tonnes_per_Hectare primary_soil_type  \
0              641.0                      3.64               NaN
1              165.0                      0.23               NaN
2              100.0                      2.78               NaN
3                2.0                      2.00               NaN
4               15.0                      3.00               NaN

  secondary_soil_type  ph_level  ...  rabi_rainfall_x summer_rainfall_x  \
0                 NaN       NaN  ...              NaN               NaN
1                 NaN       NaN  ...              NaN               NaN
2                 NaN       NaN  ...              NaN               NaN
3                 NaN       NaN  ...              NaN               NaN
4                 NaN       NaN  ...              NaN               NaN

  total_annual_rainfall_y kharif_rainfall_y  rabi_rainfall_y  \
0                     NaN               NaN              NaN
1                     NaN               NaN              NaN
2                     NaN               NaN              NaN
3                     NaN               NaN              NaN
4                     NaN               NaN              NaN

  summer_rainfall_y avg_annual_soil_moisture avg_kharif_moisture  \
0               NaN                      NaN                 NaN
1               NaN                      NaN                 NaN
2               NaN                      NaN                 NaN
3               NaN                      NaN                 NaN
4               NaN                      NaN                 NaN

  avg_rabi_moisture  avg_summer_moisture
0               NaN                  NaN
1               NaN                  NaN
2               NaN                  NaN
3               NaN                  NaN
4               NaN                  NaN

[5 rows x 44 columns]

# PART 2

## Merging Soil data + Production data

In [77]:
import pandas as pd
import numpy as np

# Define the helper function for standardizing names
def standardize_name(name):
    if isinstance(name, str):
        return name.strip().lower().replace(' ', '_').replace('-', '_')
    return name

# More aggressive name standardization for district matching
def clean_district_name(name):
    if isinstance(name, str):
        name = name.strip().lower()
        # Remove common prefixes/suffixes that might cause mismatches
        name = name.replace('district', '').replace('dt', '').replace('_district', '')
        name = name.replace('_dt', '').strip()
        # Handle special characters
        name = name.replace('-', '_').replace(' ', '_').replace('.', '')
        # Remove multiple underscores
        while '__' in name:
            name = name.replace('__', '_')
        name = name.strip('_')
        return name
    return name

In [78]:

# ==============================================================================
# Step 1: Load and Clean Production Data
# ==============================================================================
print("Loading production data...")
prod_df = pd.read_csv('D:/Work/Coding/SIH 2025/agricultural-ai-platform/data/fertilizer_model/crop_production.csv')

# Clean column names
prod_df.columns = [col.strip() for col in prod_df.columns]

# Standardize names
prod_df['State'] = prod_df['State'].apply(standardize_name)
prod_df['District'] = prod_df['District'].apply(clean_district_name)
prod_df['Crop'] = prod_df['Crop'].apply(standardize_name)

# Clean year data
prod_df['Year'] = pd.to_numeric(prod_df['Year'], errors='coerce').astype('Int64')

# Drop missing yield data
prod_df.dropna(subset=['Yield_Tonnes_per_Hectare'], inplace=True)

print(f"Production data shape: {prod_df.shape}")
print("Sample production data:")
print(prod_df[['State', 'District', 'Year', 'Crop']].head())

Loading production data...
Production data shape: (34785, 7)
Sample production data:
                         State  District  Year          Crop
0  andaman_and_nicobar_islands  nicobars  2000        banana
1  andaman_and_nicobar_islands  nicobars  2000     cashewnut
2  andaman_and_nicobar_islands  nicobars  2000        ginger
3  andaman_and_nicobar_islands  nicobars  2000     sugarcane
4  andaman_and_nicobar_islands  nicobars  2000  sweet_potato

In [79]:

# ==============================================================================
# Step 2: Load and Clean Soil Data  
# ==============================================================================
print("\nLoading soil data...")
soil_df = pd.read_csv('D:/Work/Coding/SIH 2025/agricultural-ai-platform/data/fertilizer_model/district_soil_mapping.csv')

# Check the actual column names in soil data
print("Soil data columns:", soil_df.columns.tolist())

# Standardize soil data column names (handle both uppercase and lowercase possibilities)
if 'state' in soil_df.columns:
    soil_df = soil_df.rename(columns={'state': 'State'})
if 'district' in soil_df.columns:
    soil_df = soil_df.rename(columns={'district': 'District'})

# Standardize names in soil data
soil_df['State'] = soil_df['State'].apply(standardize_name)
soil_df['District'] = soil_df['District'].apply(clean_district_name)

print(f"Soil data shape: {soil_df.shape}")
print("Sample soil data:")
print(soil_df[['State', 'District']].head())

Loading soil data...
Soil data columns: ['State', 'District', 'primary_soil_type', 'secondary_soil_type', 'ph_level', 'organic_matter_percent', 'nitrogen_level', 'phosphorus_level', 'potassium_level', 'water_holding_capacity_percent', 'drainage', 'erosion_risk', 'salinity_level', 'texture', 'depth_cm', 'elevation_meters', 'slope_percent', 'cation_exchange_capacity', 'bulk_density', 'infiltration_rate_mm_per_hour', 'available_water_capacity_mm', 'micronutrient_status', 'soil_temperature_celsius', 'major_constraints', 'land_use_pattern', 'irrigation_potential', 'groundwater_depth_meters']
Soil data shape: (787, 27)
Sample soil data:
            State               District
0  andhra_pradesh  alluri_sitharama_raju
1  andhra_pradesh             anakapalli
2  andhra_pradesh           anantapuramu
3  andhra_pradesh              annamayya
4  andhra_pradesh                bapatla

In [80]:

# ==============================================================================
# Step 3: Diagnostic - Check for mismatches
# ==============================================================================
print("\n" + "="*60)
print("DIAGNOSTIC: Checking for name mismatches")
print("="*60)

# Get unique combinations
prod_locations = set(zip(prod_df['State'], prod_df['District']))
soil_locations = set(zip(soil_df['State'], soil_df['District']))

# Find mismatches
prod_only = prod_locations - soil_locations
soil_only = soil_locations - prod_locations
common_locations = prod_locations & soil_locations

print(f"Common locations: {len(common_locations)}")
print(f"Production-only locations: {len(prod_only)}")
print(f"Soil-only locations: {len(soil_only)}")

if len(prod_only) > 0:
    print("\nFirst 10 production locations not in soil data:")
    for i, (state, district) in enumerate(list(prod_only)[:10]):
        print(f"  {i+1}. {state} - {district}")

============================================================
DIAGNOSTIC: Checking for name mismatches
============================================================
Common locations: 329
Production-only locations: 74
Soil-only locations: 457

First 10 production locations not in soil data:
  1. jharkhand - saraikela_kharsawan
  2. nagaland - nuiland
  3. west_bengal - dinajpur_uttar
  4. andaman_and_nicobar_islands - nicobars
  5. gujarat - chhotaudepur
  6. hassan - 2000_2001
  7. karnataka - belgaum
  8. andaman_and_nicobar_islands - south_andamans
  9. uttarakhand - rudra_prayag
  10. namakkal - 2005_2006

In [81]:
print("\nCreating manual mapping for common mismatches...")

# Common district name variations mapping
district_mapping = {
    # Format: 'name_in_production': 'name_in_soil'
    'nicobars': 'nicobar',
    'south_andamans': 'south_andaman', 
    'north_and_middle_andaman': 'north_and_middle_andaman',
    'alluri_sitharama_raju': 'alluri_sitharama_raju',
    'dr_br_ambedkar_konaseema': 'dr_b_r_ambedkar_konaseema',
    'east_godavari': 'east_godavari',
    'spsr_nellore': 'sri_potti_sriramulu_nellore',
    'kadapa': 'ysr_kadapa',
    'nellore': 'sri_potti_sriramulu_nellore',
    'vizianagaram': 'vizianagaram',
    'visakhapatnam': 'visakhapatnam',
    'west_godavari': 'west_godavari',
    # Add more mappings as needed
}

state_mapping = {
    # Format: 'name_in_production': 'name_in_soil'
    'andaman_and_nicobar_islands': 'andaman_and_nicobar_islands',
}

# Apply mappings to production data
prod_df['District'] = prod_df['District'].replace(district_mapping)
prod_df['State'] = prod_df['State'].replace(state_mapping)

Creating manual mapping for common mismatches...

In [82]:

# ==============================================================================
# Step 5: Perform the merge
# ==============================================================================
print("\nPerforming the merge...")

# Merge the dataframes
master_df = pd.merge(prod_df, soil_df, on=['State', 'District'], how='left')

print(f"Master dataframe shape: {master_df.shape}")

# ==============================================================================
# Step 6: Check merge quality
# ==============================================================================
print("\n" + "="*60)
print("MERGE QUALITY CHECK")
print("="*60)

Performing the merge...
Master dataframe shape: (34785, 32)

============================================================
MERGE QUALITY CHECK
============================================================

In [83]:

# Check for null values in key soil columns
soil_columns = ['ph_level', 'organic_matter_percent', 'nitrogen_level', 'phosphorus_level', 'potassium_level']
available_soil_cols = [col for col in soil_columns if col in master_df.columns]

if available_soil_cols:
    for col in available_soil_cols:
        null_count = master_df[col].isnull().sum()
        null_percentage = (null_count / len(master_df)) * 100
        print(f"{col}: {null_count} nulls ({null_percentage:.1f}%)")
else:
    print("Soil columns not found. Available columns:")
    print(master_df.columns.tolist())

ph_level: 4153 nulls (11.9%)
organic_matter_percent: 4153 nulls (11.9%)
nitrogen_level: 4153 nulls (11.9%)
phosphorus_level: 4153 nulls (11.9%)
potassium_level: 4153 nulls (11.9%)

In [84]:
master_df.head(10)

,State,District,Year,Crop,Area_Hectare,Production_Tonnes,Yield_Tonnes_per_Hectare,primary_soil_type,secondary_soil_type,ph_level,...,cation_exchange_capacity,bulk_density,infiltration_rate_mm_per_hour,available_water_capacity_mm,micronutrient_status,soil_temperature_celsius,major_constraints,land_use_pattern,irrigation_potential,groundwater_depth_meters
0,andaman_and_nicobar_islands,nicobar,2000,banana,176.0,641.0,3.64,laterite,laterite,6.4,...,11.2,1.48,7.7,192.1,adequate,32.6,waterlogging,barren,medium,27.9
1,andaman_and_nicobar_islands,nicobar,2000,cashewnut,720.0,165.0,0.23,laterite,laterite,6.4,...,11.2,1.48,7.7,192.1,adequate,32.6,waterlogging,barren,medium,27.9
2,andaman_and_nicobar_islands,nicobar,2000,ginger,36.0,100.0,2.78,laterite,laterite,6.4,...,11.2,1.48,7.7,192.1,adequate,32.6,waterlogging,barren,medium,27.9
3,andaman_and_nicobar_islands,nicobar,2000,sugarcane,1.0,2.0,2.00,laterite,laterite,6.4,...,11.2,1.48,7.7,192.1,adequate,32.6,waterlogging,barren,medium,27.9
4,andaman_and_nicobar_islands,nicobar,2000,sweet_potato,5.0,15.0,3.00,laterite,laterite,6.4,...,11.2,1.48,7.7,192.1,adequate,32.6,waterlogging,barren,medium,27.9
5,andaman_and_nicobar_islands,nicobar,2000,tapioca,40.0,169.0,4.23,laterite,laterite,6.4,...,11.2,1.48,7.7,192.1,adequate,32.6,waterlogging,barren,medium,27.9
6,andaman_and_nicobar_islands,nicobar,2001,cashewnut,719.0,192.0,0.27,laterite,laterite,6.4,...,11.2,1.48,7.7,192.1,adequate,32.6,waterlogging,barren,medium,27.9
7,andaman_and_nicobar_islands,nicobar,2001,ginger,46.0,100.0,2.17,laterite,laterite,6.4,...,11.2,1.48,7.7,192.1,adequate,32.6,waterlogging,barren,medium,27.9
8,andaman_and_nicobar_islands,nicobar,2001,sugarcane,1.0,1.0,1.00,laterite,laterite,6.4,...,11.2,1.48,7.7,192.1,adequate,32.6,waterlogging,barren,medium,27.9
9,andaman_and_nicobar_islands,nicobar,2001,sweet_potato,11.0,33.0,3.00,laterite,laterite,6.4,...,11.2,1.48,7.7,192.1,adequate,32.6,waterlogging,barren,medium,27.9

In [62]:

# ==============================================================================
# Step 7: Handle remaining unmatched records
# ==============================================================================
print("\nHandling unmatched records...")

# For records that didn't match, try to find the closest match within the same state
def find_closest_soil_match(state, district, soil_df):
    """Find the closest matching district within the same state"""
    state_soil = soil_df[soil_df['State'] == state]
    if len(state_soil) == 0:
        return None
    
    # Simple similarity check - find districts with common words
    district_words = set(district.split('_'))
    best_match = None
    best_score = 0
    
    for _, row in state_soil.iterrows():
        soil_district = row['District']
        soil_words = set(soil_district.split('_'))
        
        # Calculate word overlap
        common_words = district_words & soil_words
        score = len(common_words) / max(len(district_words), len(soil_words))
        
        if score > best_score and score > 0.3:  # At least 30% similarity
            best_score = score
            best_match = row
    
    return best_match

# Apply fuzzy matching for unmatched records
if available_soil_cols and master_df[available_soil_cols[0]].isnull().sum() > 0:
    print("Applying fuzzy matching for unmatched records...")
    
    unmatched_indices = master_df[master_df[available_soil_cols[0]].isnull()].index
    matches_found = 0
    
    for idx in unmatched_indices[:100]:  # Limit to first 100 for performance
        state = master_df.loc[idx, 'State']
        district = master_df.loc[idx, 'District']
        
        match = find_closest_soil_match(state, district, soil_df)
        if match is not None:
            # Copy soil data from the matched record
            for col in soil_df.columns:
                if col not in ['State', 'District']:
                    master_df.loc[idx, col] = match[col]
            matches_found += 1
    
    print(f"Fuzzy matching found {matches_found} additional matches")

Handling unmatched records...
Applying fuzzy matching for unmatched records...
Fuzzy matching found 0 additional matches

In [63]:

# ==============================================================================
# Step 8: Final summary and save
# ==============================================================================
print("\n" + "="*60)
print("FINAL SUMMARY")
print("="*60)

print(f"Final master dataset shape: {master_df.shape}")

if available_soil_cols:
    total_records = len(master_df)
    matched_records = master_df[available_soil_cols[0]].notna().sum()
    match_percentage = (matched_records / total_records) * 100
    
    print(f"Records with soil data: {matched_records}/{total_records} ({match_percentage:.1f}%)")
else:
    print("Could not verify soil data matches - column names may differ")

# Display sample of merged data
print("\nSample of merged data:")
display_cols = ['State', 'District', 'Year', 'Crop', 'Yield_Tonnes_per_Hectare']
if available_soil_cols:
    display_cols.extend(available_soil_cols[:3])  # Add first 3 soil columns

print(master_df[display_cols].head(10))

# Save the merged data
output_path = 'D:/Work/Coding/SIH 2025/agricultural-ai-platform/data/master_df_combined.csv'
master_df.to_csv(output_path, index=False)
print(f"\n✅ Master dataframe saved to: {output_path}")

# Return the master dataframe for further use
print("\n🎉 Merge completed! Use 'master_df' for your analysis.")

============================================================
FINAL SUMMARY
============================================================
Final master dataset shape: (34785, 32)
Records with soil data: 30632/34785 (88.1%)

Sample of merged data:
                         State District  Year          Crop  \
0  andaman_and_nicobar_islands  nicobar  2000        banana
1  andaman_and_nicobar_islands  nicobar  2000     cashewnut
2  andaman_and_nicobar_islands  nicobar  2000        ginger
3  andaman_and_nicobar_islands  nicobar  2000     sugarcane
4  andaman_and_nicobar_islands  nicobar  2000  sweet_potato
5  andaman_and_nicobar_islands  nicobar  2000       tapioca
6  andaman_and_nicobar_islands  nicobar  2001     cashewnut
7  andaman_and_nicobar_islands  nicobar  2001        ginger
8  andaman_and_nicobar_islands  nicobar  2001     sugarcane
9  andaman_and_nicobar_islands  nicobar  2001  sweet_potato

   Yield_Tonnes_per_Hectare  ph_level  organic_matter_percent nitrogen_level
0                      3.64       6.4                     1.3         medium
1                      0.23       6.4                     1.3         medium
2                      2.78       6.4                     1.3         medium
3                      2.00       6.4                     1.3         medium
4                      3.00       6.4                     1.3         medium
5                      4.23       6.4                     1.3         medium
6                      0.27       6.4                     1.3         medium
7                      2.17       6.4                     1.3         medium
8                      1.00       6.4                     1.3         medium
9                      3.00       6.4                     1.3         medium

✅ Master dataframe saved to: D:/Work/Coding/SIH 2025/agricultural-ai-platform/data/master_df_combined.csv

🎉 Merge completed! Use 'master_df' for your analysis.

In [65]:
master_df.head(10)

,State,District,Year,Crop,Area_Hectare,Production_Tonnes,Yield_Tonnes_per_Hectare,primary_soil_type,secondary_soil_type,ph_level,...,cation_exchange_capacity,bulk_density,infiltration_rate_mm_per_hour,available_water_capacity_mm,micronutrient_status,soil_temperature_celsius,major_constraints,land_use_pattern,irrigation_potential,groundwater_depth_meters
0,andaman_and_nicobar_islands,nicobar,2000,banana,176.0,641.0,3.64,laterite,laterite,6.4,...,11.2,1.48,7.7,192.1,adequate,32.6,waterlogging,barren,medium,27.9
1,andaman_and_nicobar_islands,nicobar,2000,cashewnut,720.0,165.0,0.23,laterite,laterite,6.4,...,11.2,1.48,7.7,192.1,adequate,32.6,waterlogging,barren,medium,27.9
2,andaman_and_nicobar_islands,nicobar,2000,ginger,36.0,100.0,2.78,laterite,laterite,6.4,...,11.2,1.48,7.7,192.1,adequate,32.6,waterlogging,barren,medium,27.9
3,andaman_and_nicobar_islands,nicobar,2000,sugarcane,1.0,2.0,2.00,laterite,laterite,6.4,...,11.2,1.48,7.7,192.1,adequate,32.6,waterlogging,barren,medium,27.9
4,andaman_and_nicobar_islands,nicobar,2000,sweet_potato,5.0,15.0,3.00,laterite,laterite,6.4,...,11.2,1.48,7.7,192.1,adequate,32.6,waterlogging,barren,medium,27.9
5,andaman_and_nicobar_islands,nicobar,2000,tapioca,40.0,169.0,4.23,laterite,laterite,6.4,...,11.2,1.48,7.7,192.1,adequate,32.6,waterlogging,barren,medium,27.9
6,andaman_and_nicobar_islands,nicobar,2001,cashewnut,719.0,192.0,0.27,laterite,laterite,6.4,...,11.2,1.48,7.7,192.1,adequate,32.6,waterlogging,barren,medium,27.9
7,andaman_and_nicobar_islands,nicobar,2001,ginger,46.0,100.0,2.17,laterite,laterite,6.4,...,11.2,1.48,7.7,192.1,adequate,32.6,waterlogging,barren,medium,27.9
8,andaman_and_nicobar_islands,nicobar,2001,sugarcane,1.0,1.0,1.00,laterite,laterite,6.4,...,11.2,1.48,7.7,192.1,adequate,32.6,waterlogging,barren,medium,27.9
9,andaman_and_nicobar_islands,nicobar,2001,sweet_potato,11.0,33.0,3.00,laterite,laterite,6.4,...,11.2,1.48,7.7,192.1,adequate,32.6,waterlogging,barren,medium,27.9

## Adding soil moisture and rainfall data also to make master table

In [67]:
import pandas as pd
import numpy as np

# Define helper functions for standardizing names
def standardize_name(name):
    if isinstance(name, str):
        return name.strip().lower().replace(' ', '_').replace('-', '_')
    return name

def clean_district_name(name):
    if isinstance(name, str):
        name = name.strip().lower()
        name = name.replace('district', '').replace('dt', '').replace('_district', '')
        name = name.replace('_dt', '').strip()
        name = name.replace('-', '_').replace(' ', '_').replace('.', '')
        while '__' in name:
            name = name.replace('__', '_')
        name = name.strip('_')
        return name
    return name

# Define seasons function
def get_season(month):
    if 6 <= month <= 9:
        return 'kharif'
    if 10 <= month <= 12 or 1 <= month <= 3:
        return 'rabi'
    return 'summer'

print("🚀 Starting Master Dataset Creation...")
print("="*60)

🚀 Starting Master Dataset Creation...
============================================================

In [68]:

# ==============================================================================
# Step 1: Load and Process Rainfall Data
# ==============================================================================
print("📊 Loading and processing rainfall data...")

rain_df = pd.read_csv('D:/Work/Coding/SIH 2025/agricultural-ai-platform/data/fertilizer_model/rainfall_combined.csv')

# Clean rainfall data
rain_df['State'] = rain_df['State'].apply(standardize_name)
rain_df['District'] = rain_df['District'].apply(clean_district_name)
rain_df['Year'] = pd.to_numeric(rain_df['Year'], errors='coerce').astype('Int64')
rain_df['Month'] = pd.to_numeric(rain_df['Month'], errors='coerce').astype('Int64')

# Add season column
rain_df['season'] = rain_df['Month'].apply(get_season)

# Aggregate seasonal rainfall
seasonal_rain = rain_df.groupby(['State', 'District', 'Year', 'season'])['Avg_rainfall'].sum().unstack(fill_value=0).reset_index()
seasonal_rain.columns = ['State', 'District', 'Year', 'kharif_rainfall', 'rabi_rainfall', 'summer_rainfall']

# Calculate total annual rainfall
annual_rain = rain_df.groupby(['State', 'District', 'Year'])['Avg_rainfall'].sum().reset_index()
annual_rain = annual_rain.rename(columns={'Avg_rainfall': 'total_annual_rainfall'})

# Merge seasonal and annual rainfall
yearly_rainfall_df = pd.merge(annual_rain, seasonal_rain, on=['State', 'District', 'Year'])

print(f"✅ Rainfall data processed: {yearly_rainfall_df.shape}")

📊 Loading and processing rainfall data...
✅ Rainfall data processed: (1564, 7)

In [70]:

# ==============================================================================
# Step 2: Load and Process Soil Moisture Data (CORRECTED)
# ==============================================================================
print("🌱 Loading and processing soil moisture data...")

# Load the correct soil moisture data file
soil_moisture_df = pd.read_csv('D:/Work/Coding/SIH 2025/agricultural-ai-platform/data/soil_moisture/soil_moisture_combined.csv')

# Clean soil moisture data
soil_moisture_df['State'] = soil_moisture_df['State'].apply(standardize_name)
soil_moisture_df['District'] = soil_moisture_df['District'].apply(clean_district_name)
soil_moisture_df['Year'] = pd.to_numeric(soil_moisture_df['Year'], errors='coerce').astype('Int64')
soil_moisture_df['Month'] = pd.to_numeric(soil_moisture_df['Month'], errors='coerce').astype('Int64')

# Drop rows where year could not be converted
soil_moisture_df.dropna(subset=['Year'], inplace=True)

# Add season column
soil_moisture_df['season'] = soil_moisture_df['Month'].apply(get_season)

# Aggregate seasonal soil moisture (using the correct column name)
seasonal_moisture = soil_moisture_df.groupby(['State', 'District', 'Year', 'season'])['Avg_smlvl_at15cm'].mean().unstack(fill_value=0).reset_index()
seasonal_moisture.columns = ['State', 'District', 'Year', 'avg_kharif_moisture', 'avg_rabi_moisture', 'avg_summer_moisture']

# Calculate annual average soil moisture
annual_moisture = soil_moisture_df.groupby(['State', 'District', 'Year'])['Avg_smlvl_at15cm'].mean().reset_index()
annual_moisture = annual_moisture.rename(columns={'Avg_smlvl_at15cm': 'avg_annual_soil_moisture'})

# Merge seasonal and annual moisture data
yearly_soil_moisture_df = pd.merge(annual_moisture, seasonal_moisture, on=['State', 'District', 'Year'])

print(f"✅ Soil moisture data processed: {yearly_soil_moisture_df.shape}")

🌱 Loading and processing soil moisture data...
✅ Soil moisture data processed: (5866, 7)

In [71]:

# ==============================================================================
# Step 3: Load and Process Production Data
# ==============================================================================
print("🌾 Loading and processing production data...")

prod_df = pd.read_csv('D:/Work/Coding/SIH 2025/agricultural-ai-platform/data/fertilizer_model/crop_production.csv')

# Clean production data
prod_df.columns = [col.strip() for col in prod_df.columns]
prod_df['State'] = prod_df['State'].apply(standardize_name)
prod_df['District'] = prod_df['District'].apply(clean_district_name)
prod_df['Crop'] = prod_df['Crop'].apply(standardize_name)
prod_df['Year'] = pd.to_numeric(prod_df['Year'], errors='coerce').astype('Int64')

# Drop missing yield data
prod_df.dropna(subset=['Yield_Tonnes_per_Hectare'], inplace=True)

print(f"✅ Production data processed: {prod_df.shape}")

🌾 Loading and processing production data...
✅ Production data processed: (34785, 7)

In [72]:

# ==============================================================================
# Step 4: Load and Process Soil Data
# ==============================================================================
print("🏔️ Loading and processing soil data...")

soil_df = pd.read_csv('D:/Work/Coding/SIH 2025/agricultural-ai-platform/data/fertilizer_model/district_soil_mapping.csv')

# Standardize soil data column names
if 'state' in soil_df.columns:
    soil_df = soil_df.rename(columns={'state': 'State'})
if 'district' in soil_df.columns:
    soil_df = soil_df.rename(columns={'district': 'District'})

# Clean soil data
soil_df['State'] = soil_df['State'].apply(standardize_name)
soil_df['District'] = soil_df['District'].apply(clean_district_name)

print(f"✅ Soil data processed: {soil_df.shape}")

🏔️ Loading and processing soil data...
✅ Soil data processed: (787, 27)

## Making Master Table

In [85]:

# ==============================================================================
# Step 5: Create Master Dataset by Merging All Data
# ==============================================================================
print("\n🔄 Creating master dataset...")
print("="*60)

# # Start with production data as the base
# master_df = prod_df.copy()
# print(f"Base (production): {master_df.shape}")

# # Merge with soil data (no Year needed for soil characteristics)
# master_df = pd.merge(master_df, soil_df, on=['State', 'District'], how='left')
# print(f"After soil merge: {master_df.shape}")

# Merge with rainfall data (includes Year)
master_df = pd.merge(master_df, yearly_rainfall_df, on=['State', 'District', 'Year'], how='left')
print(f"After rainfall merge: {master_df.shape}")

# Merge with soil moisture data (includes Year)
master_df = pd.merge(master_df, yearly_soil_moisture_df, on=['State', 'District', 'Year'], how='left')
print(f"After soil moisture merge: {master_df.shape}")

🔄 Creating master dataset...
============================================================
After rainfall merge: (34785, 36)
After soil moisture merge: (34785, 40)

In [74]:

# ==============================================================================
# Step 6: Data Quality Check
# ==============================================================================
print("\n📊 Data Quality Assessment:")
print("="*60)

print(f"Final master dataset shape: {master_df.shape}")
print(f"Date range: {master_df['Year'].min()} - {master_df['Year'].max()}")
print(f"Unique states: {master_df['State'].nunique()}")
print(f"Unique districts: {master_df['District'].nunique()}")
print(f"Unique crops: {master_df['Crop'].nunique()}")

# Check for missing values
print("\nMissing values per column:")
missing_summary = master_df.isnull().sum()
for col, missing_count in missing_summary.items():
    if missing_count > 0:
        missing_pct = (missing_count / len(master_df)) * 100
        print(f"  {col}: {missing_count:,} ({missing_pct:.1f}%)")

📊 Data Quality Assessment:
============================================================
Final master dataset shape: (34785, 40)
Date range: 1994 - 2027
Unique states: 45
Unique districts: 398
Unique crops: 101

Missing values per column:
  Area_Hectare: 49 (0.1%)
  Production_Tonnes: 712 (2.0%)
  primary_soil_type: 4,554 (13.1%)
  secondary_soil_type: 4,554 (13.1%)
  ph_level: 4,554 (13.1%)
  organic_matter_percent: 4,554 (13.1%)
  nitrogen_level: 4,554 (13.1%)
  phosphorus_level: 4,554 (13.1%)
  potassium_level: 4,554 (13.1%)
  water_holding_capacity_percent: 4,554 (13.1%)
  drainage: 4,554 (13.1%)
  erosion_risk: 4,554 (13.1%)
  salinity_level: 4,554 (13.1%)
  texture: 4,554 (13.1%)
  depth_cm: 4,554 (13.1%)
  elevation_meters: 4,554 (13.1%)
  slope_percent: 4,554 (13.1%)
  cation_exchange_capacity: 4,554 (13.1%)
  bulk_density: 4,554 (13.1%)
  infiltration_rate_mm_per_hour: 4,554 (13.1%)
  available_water_capacity_mm: 4,554 (13.1%)
  micronutrient_status: 4,554 (13.1%)
  soil_temperature_celsius: 4,554 (13.1%)
  major_constraints: 4,554 (13.1%)
  land_use_pattern: 4,554 (13.1%)
  irrigation_potential: 4,554 (13.1%)
  groundwater_depth_meters: 4,554 (13.1%)
  total_annual_rainfall: 33,620 (96.7%)
  kharif_rainfall: 33,620 (96.7%)
  rabi_rainfall: 33,620 (96.7%)
  summer_rainfall: 33,620 (96.7%)
  avg_annual_soil_moisture: 30,296 (87.1%)
  avg_kharif_moisture: 30,296 (87.1%)
  avg_rabi_moisture: 30,296 (87.1%)
  avg_summer_moisture: 30,296 (87.1%)

In [86]:

# ==============================================================================
# Step 7: Save Master Dataset
# ==============================================================================
print("\n💾 Saving master dataset...")

output_path = 'D:/Work/Coding/SIH 2025/agricultural-ai-platform/data/master_df_combined.csv'
master_df.to_csv(output_path, index=False)

import os
file_size_mb = os.path.getsize(output_path) / (1024*1024)

print(f"✅ Master dataframe saved successfully!")
print(f"📁 File path: {output_path}")
print(f"📊 Shape: {master_df.shape}")
print(f"📦 File size: {file_size_mb:.2f} MB")

💾 Saving master dataset...
✅ Master dataframe saved successfully!
📁 File path: D:/Work/Coding/SIH 2025/agricultural-ai-platform/data/master_df_combined.csv
📊 Shape: (34785, 40)
📦 File size: 7.12 MB

In [87]:

# ==============================================================================
# Step 8: Display Sample Data
# ==============================================================================
print("\n📋 Sample of final master dataset:")
print("="*60)

# Select key columns for display
display_cols = ['State', 'District', 'Year', 'Crop', 'Yield_Tonnes_per_Hectare', 
                'total_annual_rainfall', 'avg_annual_soil_moisture']

# Add soil columns if they exist
soil_cols = ['ph_level', 'organic_matter_percent', 'nitrogen_level']
available_soil_cols = [col for col in soil_cols if col in master_df.columns]
display_cols.extend(available_soil_cols[:2])  # Add first 2 soil columns

print(master_df[display_cols].head(10))

print("\n🎉 Master dataset creation completed successfully!")
print("🔍 Use 'master_df' variable for further analysis")

📋 Sample of final master dataset:
============================================================
                         State District  Year          Crop  \
0  andaman_and_nicobar_islands  nicobar  2000        banana
1  andaman_and_nicobar_islands  nicobar  2000     cashewnut
2  andaman_and_nicobar_islands  nicobar  2000        ginger
3  andaman_and_nicobar_islands  nicobar  2000     sugarcane
4  andaman_and_nicobar_islands  nicobar  2000  sweet_potato
5  andaman_and_nicobar_islands  nicobar  2000       tapioca
6  andaman_and_nicobar_islands  nicobar  2001     cashewnut
7  andaman_and_nicobar_islands  nicobar  2001        ginger
8  andaman_and_nicobar_islands  nicobar  2001     sugarcane
9  andaman_and_nicobar_islands  nicobar  2001  sweet_potato

   Yield_Tonnes_per_Hectare  total_annual_rainfall  avg_annual_soil_moisture  \
0                      3.64                    NaN                       NaN
1                      0.23                    NaN                       NaN
2                      2.78                    NaN                       NaN
3                      2.00                    NaN                       NaN
4                      3.00                    NaN                       NaN
5                      4.23                    NaN                       NaN
6                      0.27                    NaN                       NaN
7                      2.17                    NaN                       NaN
8                      1.00                    NaN                       NaN
9                      3.00                    NaN                       NaN

   ph_level  organic_matter_percent
0       6.4                     1.3
1       6.4                     1.3
2       6.4                     1.3
3       6.4                     1.3
4       6.4                     1.3
5       6.4                     1.3
6       6.4                     1.3
7       6.4                     1.3
8       6.4                     1.3
9       6.4                     1.3

🎉 Master dataset creation completed successfully!
🔍 Use 'master_df' variable for further analysis

In [88]:
# Let's analyze your data coverage
print("=== DATA COVERAGE ANALYSIS ===")

# Check production data coverage by year
prod_years = master_df['Year'].value_counts().sort_index()
print(f"Production data spans: {master_df['Year'].min()} - {master_df['Year'].max()}")
print(f"Most data from: {prod_years.idxmax()} ({prod_years.max()} records)")

# Check weather data coverage
weather_coverage = master_df['total_annual_rainfall'].notna().sum()
print(f"Weather data coverage: {weather_coverage}/{len(master_df)} ({weather_coverage/len(master_df)*100:.1f}%)")

# Check soil data coverage
soil_coverage = master_df['ph_level'].notna().sum()
print(f"Soil data coverage: {soil_coverage}/{len(master_df)} ({soil_coverage/len(master_df)*100:.1f}%)")

# This is normal for agricultural datasets!

=== DATA COVERAGE ANALYSIS ===
Production data spans: 1994 - 2027
Most data from: 2003 (2879 records)
Weather data coverage: 1165/34785 (3.3%)
Soil data coverage: 30632/34785 (88.1%)

## How to Handle NaN Values for ML:

In [ ]:
# Option 1: Use only complete records
complete_records = master_df.dropna(subset=['ph_level', 'total_annual_rainfall', 'avg_annual_soil_moisture'])
print(f"Complete records: {len(complete_records)}")

# Option 2: Fill missing values strategically
# For soil data - use district/state averages
soil_cols = ['ph_level', 'organic_matter_percent', 'nitrogen_level']
for col in soil_cols:
    if col in master_df.columns:
        # Fill with state averages
        master_df[col] = master_df.groupby('State')[col].transform(
            lambda x: x.fillna(x.mean())
        )

# For weather data - use historical averages or interpolation
weather_cols = ['total_annual_rainfall', 'avg_annual_soil_moisture']
for col in weather_cols:
    if col in master_df.columns:
        # Fill with district historical averages
        master_df[col] = master_df.groupby(['State', 'District'])[col].transform(
            lambda x: x.fillna(x.mean())
        )

print("✅ NaN values handled for ML modeling")

## Extra analysis

In [89]:
master_df['Year'].unique()

<IntegerArray>
[2000, 2001, 2002, 2003, 2004, 2005, 2006, 2010, 2011, 2012, 2013, 2014, 2015,
 2016, 2017, 2018, 2019, 2020, 2021, 2022, 1998, 1999, 2008, 2009, 2007, 1997,
 2027, 1994, 2026]
Length: 29, dtype: Int64

In [91]:
# Check the problematic years in detail
print("=== YEAR DATA INVESTIGATION ===")

# Count records by year
year_counts = master_df['Year'].value_counts().sort_index()
print("Records by year:")
print(year_counts)

# Focus on suspicious future years
future_years = master_df[master_df['Year'] > 2025]
print(f"\n🚨 Found {len(future_years)} records from future years (2026+)")

if len(future_years) > 0:
    print("\nFuture year data breakdown:")
    print(future_years.groupby(['Year', 'State', 'District']).size().reset_index(name='count'))
    
    print("\nSample of future year records:")
    print(future_years[['State', 'District', 'Year', 'Crop', 'Yield_Tonnes_per_Hectare']].head(10))

# Check if these might be academic/projected years
print(f"\nYear range: {master_df['Year'].min()} to {master_df['Year'].max()}")

=== YEAR DATA INVESTIGATION ===
Records by year:
Year
1994       7
1997     981
1998    1140
1999    1327
2000    1702
2001    1550
2002    2730
2003    2879
2004    1555
2005    1442
2006    1396
2007    1194
2008    1335
2009    1417
2010    1055
2011    1247
2012    1091
2013    1236
2014    1087
2015    1067
2016    1085
2017    1079
2018    1149
2019    1084
2020    1015
2021     979
2022     924
2026      21
2027      11
Name: count, dtype: Int64

🚨 Found 32 records from future years (2026+)

Future year data breakdown:
   Year        State   District  count
0  2026  thiruvallur  2005_2006      8
1  2026     vaishali  2003_2004     13
2  2027       mysore  2006_2007     11

Sample of future year records:
        State   District  Year          Crop  Yield_Tonnes_per_Hectare
22948  mysore  2006_2007  2027      arecanut                 26.000000
22949  mysore  2006_2007  2027        banana                  0.000493
22950  mysore  2006_2007  2027     coriander                186.000000
22951  mysore  2006_2007  2027    cottonlint                  0.000018
22952  mysore  2006_2007  2027  dry_chillies                  0.000927
22953  mysore  2006_2007  2027         onion                 42.000000
22954  mysore  2006_2007  2027        potato                  0.005378
22955  mysore  2006_2007  2027     sugarcane                  0.000089
22956  mysore  2006_2007  2027  sweet_potato                 15.000000
22957  mysore  2006_2007  2027       tobacco                  5.000000

Year range: 1994 to 2027

In [92]:
# Check the problematic years in detail
print("=== YEAR DATA INVESTIGATION ===")

# Count records by year
year_counts = master_df['Year'].value_counts().sort_index()
print("Records by year:")
print(year_counts)

# Focus on suspicious future years
future_years = master_df[master_df['Year'] > 2025]
print(f"\n🚨 Found {len(future_years)} records from future years (2026+)")

if len(future_years) > 0:
    print("\nFuture year data breakdown:")
    print(future_years.groupby(['Year', 'State', 'District']).size().reset_index(name='count'))
    
    print("\nSample of future year records:")
    print(future_years[['State', 'District', 'Year', 'Crop', 'Yield_Tonnes_per_Hectare']].head(10))

# Check if these might be academic/projected years
print(f"\nYear range: {master_df['Year'].min()} to {master_df['Year'].max()}")

=== YEAR DATA INVESTIGATION ===
Records by year:
Year
1994       7
1997     981
1998    1140
1999    1327
2000    1702
2001    1550
2002    2730
2003    2879
2004    1555
2005    1442
2006    1396
2007    1194
2008    1335
2009    1417
2010    1055
2011    1247
2012    1091
2013    1236
2014    1087
2015    1067
2016    1085
2017    1079
2018    1149
2019    1084
2020    1015
2021     979
2022     924
2026      21
2027      11
Name: count, dtype: Int64

🚨 Found 32 records from future years (2026+)

Future year data breakdown:
   Year        State   District  count
0  2026  thiruvallur  2005_2006      8
1  2026     vaishali  2003_2004     13
2  2027       mysore  2006_2007     11

Sample of future year records:
        State   District  Year          Crop  Yield_Tonnes_per_Hectare
22948  mysore  2006_2007  2027      arecanut                 26.000000
22949  mysore  2006_2007  2027        banana                  0.000493
22950  mysore  2006_2007  2027     coriander                186.000000
22951  mysore  2006_2007  2027    cottonlint                  0.000018
22952  mysore  2006_2007  2027  dry_chillies                  0.000927
22953  mysore  2006_2007  2027         onion                 42.000000
22954  mysore  2006_2007  2027        potato                  0.005378
22955  mysore  2006_2007  2027     sugarcane                  0.000089
22956  mysore  2006_2007  2027  sweet_potato                 15.000000
22957  mysore  2006_2007  2027       tobacco                  5.000000

Year range: 1994 to 2027

In [93]:
# ==============================================================================
# COMPREHENSIVE DATA CLEANING
# ==============================================================================
print("🧹 Comprehensive data cleaning...")

# Check for year-like patterns in District column
print("Suspicious district entries (containing years):")
year_pattern_districts = master_df['District'].str.contains(r'\d{4}', na=False)
suspicious_districts = master_df[year_pattern_districts]['District'].unique()
print(f"Found {len(suspicious_districts)} suspicious district entries:")
for dist in suspicious_districts[:10]:
    print(f"  - {dist}")

# Check for impossible years
print(f"\nYear range before cleaning: {master_df['Year'].min()} - {master_df['Year'].max()}")
print(f"Future years count: {(master_df['Year'] > 2025).sum()}")
print(f"Very old years count: {(master_df['Year'] < 1990).sum()}")

# Clean the data
print("\n🔧 Applying fixes...")

# Remove records with year-like patterns in District column
clean_mask = ~master_df['District'].str.contains(r'\d{4}', na=False)
master_df_clean = master_df[clean_mask].copy()

# Remove future years (after 2025)
master_df_clean = master_df_clean[master_df_clean['Year'] <= 2025]

# Remove very old years (before 1990) - likely data errors
master_df_clean = master_df_clean[master_df_clean['Year'] >= 1990]

# Remove any remaining invalid entries
master_df_clean = master_df_clean.dropna(subset=['State', 'District', 'Year', 'Crop'])

print(f"\n📊 Cleaning Results:")
print(f"Original records: {len(master_df):,}")
print(f"After cleaning: {len(master_df_clean):,}")
print(f"Removed: {len(master_df) - len(master_df_clean):,} ({((len(master_df) - len(master_df_clean))/len(master_df)*100):.1f}%)")
print(f"New year range: {master_df_clean['Year'].min()} - {master_df_clean['Year'].max()}")
print(f"Valid districts: {master_df_clean['District'].nunique()}")

🧹 Comprehensive data cleaning...
Suspicious district entries (containing years):
Found 16 suspicious district entries:
  - 2000_2001
  - 2020_2021
  - 2021_2022
  - 2013_2014
  - 2006_2007
  - 1998_1999
  - 1999_2000
  - 2001_2002
  - 2002_2003
  - 2003_2004

Year range before cleaning: 1994 - 2027
Future years count: 32
Very old years count: 0

🔧 Applying fixes...

📊 Cleaning Results:
Original records: 34,785
After cleaning: 34,562
Removed: 223 (0.6%)
New year range: 1997 - 2022
Valid districts: 382

In [94]:
# Check for other data quality issues
print("\n🔍 Additional Quality Checks:")

# Check for reasonable yield values
print(f"Negative yields: {(master_df_clean['Yield_Tonnes_per_Hectare'] < 0).sum()}")
print(f"Extremely high yields (>50): {(master_df_clean['Yield_Tonnes_per_Hectare'] > 50).sum()}")
print(f"Zero yields: {(master_df_clean['Yield_Tonnes_per_Hectare'] == 0).sum()}")

# Check state names
print(f"\nUnique states: {master_df_clean['State'].nunique()}")
print("Sample states:", master_df_clean['State'].unique()[:10])

# Check for any remaining suspicious patterns
suspicious_states = master_df_clean['State'].str.contains(r'\d{4}', na=False)
if suspicious_states.any():
    print("⚠️ Suspicious state entries found:")
    print(master_df_clean[suspicious_states]['State'].unique())

# Final validation
print(f"\n✅ Final Dataset Summary:")
print(f"Records: {len(master_df_clean):,}")
print(f"Years: {master_df_clean['Year'].min()} - {master_df_clean['Year'].max()}")
print(f"States: {master_df_clean['State'].nunique()}")
print(f"Districts: {master_df_clean['District'].nunique()}")
print(f"Crops: {master_df_clean['Crop'].nunique()}")

🔍 Additional Quality Checks:
Negative yields: 0
Extremely high yields (>50): 2887
Zero yields: 1670

Unique states: 33
Sample states: ['andaman_and_nicobar_islands' 'andhra_pradesh' 'arunachal_pradesh'
 'assam' 'bihar' 'chandigarh' 'chhattisgarh' 'delhi' 'goa' 'gujarat']

✅ Final Dataset Summary:
Records: 34,562
Years: 1997 - 2022
States: 33
Districts: 382
Crops: 101

In [96]:
# Investigate high yields
high_yields = master_df_clean[master_df_clean['Yield_Tonnes_per_Hectare'] > 50]
print("🔍 Analyzing High Yields (>50 tonnes/hectare):")
print(f"Count: {len(high_yields)}")

# Check which crops have high yields
crop_high_yields = high_yields.groupby('Crop')['Yield_Tonnes_per_Hectare'].agg(['count', 'mean', 'max']).sort_values('max', ascending=False)
print("\nTop crops with highest yields:")
print(crop_high_yields.head(10))

# Some crops like sugarcane, potato can legitimately have >50 tonnes/hectare
# Check if these are reasonable
print("\nSample high yield records:")
print(high_yields[['State', 'District', 'Crop', 'Yield_Tonnes_per_Hectare']].head(10))

🔍 Analyzing High Yields (>50 tonnes/hectare):
Count: 2887

Top crops with highest yields:
              count        mean     max
Crop
coconut           5  408.716000  494.62
sugarcane      2581   76.446292  314.74
potato            5  207.152000  311.02
banana          221   73.865837  258.07
onion             3  109.443333  204.08
cottonlint        6   85.283333  182.65
papaya           32  109.950625  130.50
sweet_potato      2  105.500000  127.00
tapioca          18   55.086667   70.52
cabbage           6   60.120000   63.60

Sample high yield records:
                           State       District        Crop  \
188  andaman_and_nicobar_islands  south_andaman     tapioca
196               andhra_pradesh      anantapur   sugarcane
200               andhra_pradesh      anantapur   sugarcane
205               andhra_pradesh      anantapur   sugarcane
212               andhra_pradesh      anantapur   sugarcane
217               andhra_pradesh      anantapur      banana
228               andhra_pradesh      anantapur      papaya
229               andhra_pradesh      anantapur  pome_fruit
231               andhra_pradesh      anantapur   sugarcane
248               andhra_pradesh      anantapur  pome_fruit

     Yield_Tonnes_per_Hectare
188                     51.03
196                     94.14
200                     94.03
205                     89.42
212                     86.67
217                     52.95
228                    130.45
229                     52.02
231                     68.33
248                     57.14

In [97]:
# ==============================================================================
# FINAL DATASET PREPARATION FOR ML
# ==============================================================================
print("🎯 Preparing final dataset for ML models...")

# Option 1: Keep all data (recommended for agricultural analysis)
final_df = master_df_clean.copy()

# Option 2: Remove extreme outliers if needed (uncomment if required)
# Remove yields > 200 (clearly unrealistic for most crops)
# final_df = final_df[final_df['Yield_Tonnes_per_Hectare'] <= 200]

# Option 3: Handle zero yields (choose one approach)
# Keep zeros (crop failures are real agricultural events)
# OR replace zeros with small positive value if needed for log transformations
# final_df.loc[final_df['Yield_Tonnes_per_Hectare'] == 0, 'Yield_Tonnes_per_Hectare'] = 0.01

# Save the final cleaned dataset
final_output_path = 'D:/Work/Coding/SIH 2025/agricultural-ai-platform/data/master_df_final_clean.csv'
final_df.to_csv(final_output_path, index=False)

import os
file_size_mb = os.path.getsize(final_output_path) / (1024*1024)

print(f"✅ Final cleaned dataset saved!")
print(f"📁 File: {final_output_path}")
print(f"📊 Shape: {final_df.shape}")
print(f"📦 Size: {file_size_mb:.2f} MB")
print(f"📅 Years: {final_df['Year'].min()}-{final_df['Year'].max()}")
print(f"🌾 Crops: {final_df['Crop'].nunique()}")
print(f"📍 Locations: {final_df['State'].nunique()} states, {final_df['District'].nunique()} districts")

# Update working dataframe
master_df = final_df
print("\n🎉 Dataset ready for ML modeling!")

🎯 Preparing final dataset for ML models...
✅ Final cleaned dataset saved!
📁 File: D:/Work/Coding/SIH 2025/agricultural-ai-platform/data/master_df_final_clean.csv
📊 Shape: (34562, 40)
📦 Size: 7.10 MB
📅 Years: 1997-2022
🌾 Crops: 101
📍 Locations: 33 states, 382 districts

🎉 Dataset ready for ML modeling!

In [ ]:
# Save the properly cleaned dataset
output_path_clean = 'D:/Work/Coding/SIH 2025/agricultural-ai-platform/data/master_df_cleaned.csv'
master_df_clean.to_csv(output_path_clean, index=False)

import os
file_size_mb = os.path.getsize(output_path_clean) / (1024*1024)

print(f"\n💾 Cleaned dataset saved:")
print(f"📁 File: {output_path_clean}")
print(f"📊 Shape: {master_df_clean.shape}")
print(f"📦 Size: {file_size_mb:.2f} MB")

# Update the working dataframe
master_df = master_df_clean
print("\n🎉 Data cleaning completed! Use 'master_df' for analysis.")

In [90]:
master_df['District'].unique()

array(['nicobar', 'north_and_middle_andaman', 'south_andaman',
       'alluri_sitharama_raju', 'anantapur', 'chittoor', 'east_godavari',
       'eluru', 'guntur', 'ysr_kadapa', 'krishna', 'kurnool', 'prakasam',
       'sri_potti_sriramulu_nellore', 'srikakulam', 'anjaw', 'changlang',
       'dibang_valley', 'east_kameng', 'east_siang', 'kamle', 'kra_daadi',
       'kurung_kumey', 'leparada', 'lohit', 'longding',
       'lower_dibang_valley', 'lower_siang', 'lower_subansiri', 'namsai',
       'baksa', 'barpeta', 'biswanath', 'bongaigaon', 'cachar',
       'charaideo', 'chirang', 'darrang', 'dhemaji', 'dhubri',
       'dibrugarh', 'dima_hasao', 'goalpara', 'araria', 'arwal',
       'aurangabad', 'banka', 'begusarai', 'bhagalpur', 'bhojpur',
       'buxar', 'darbhanga', 'gaya', 'gopalganj', 'jamui', 'chandigarh',
       'balod', 'baloda_bazar', 'balrampur', 'bastar', 'bemetara',
       'bijapur', 'bilaspur', 'dantewada', 'dhamtari', 'durg',
       'gariyaband', 'gaurella_pendra_marwahi', 'janjgir_champa',
       'jashpur', 'delhi_total', 'north_goa', 'south_goa', 'ahmadabad',
       'amreli', 'anand', 'aravalli', 'banas_kantha', 'bharuch',
       'bhavnagar', 'botad', 'chhotaudepur', 'dang', 'devbhumi_dwarka',
       'dohad', 'gandhinagar', 'gir_somnath', 'ambala', 'bhiwani',
       'charki_dadri', 'faridabad', 'fatehabad', 'gurgaon', 'hisar',
       'jhajjar', 'jind', 'kaithal', 'karnal', 'kurukshetra', '2000_2001',
       'chamba', 'hamirpur', 'kangra', 'kinnaur', 'kullu',
       'lahul_and_spiti', 'mandi', 'shimla', 'sirmaur', 'solan', 'una',
       'anantnag', 'badgam', 'baramulla', 'doda', 'jammu', 'kargil',
       'kathua', 'kishtwar', 'kupwara', 'leh_ladakh', 'poonch', 'pulwama',
       'rajauri', 'samba', 'srinagar', 'udhampur', 'bokaro', 'chatra',
       'deoghar', 'dhanbad', 'dumka', 'east_singhbum', 'garhwa',
       'giridih', 'godda', 'gumla', 'hazaribagh', 'koderma', 'latehar',
       'lohardaga', 'pakur', 'palamu', 'ranchi', 'sahebganj',
       'saraikela_kharsawan', 'simdega', 'west_singhbhum', '2020_2021',
       '2021_2022', 'bagalkot', 'bangalore_rural', 'belgaum', 'bellary',
       'bengaluru_urban', 'bidar', 'chamarajanagar', 'chikballapur',
       'chikmagalur', 'chitradurga', 'alappuzha', 'ernakulam', 'idukki',
       'kannur', 'kasaragod', 'kollam', 'kottayam', 'kozhikode',
       'malappuram', 'palakkad', 'agar_malwa', 'alirajpur', 'anuppur',
       'ashoknagar', 'balaghat', 'barwani', 'betul', 'bhind', 'bhopal',
       'burhanpur', 'chhatarpur', 'chhindwara', 'ahilyanagar', 'akola',
       'amravati', 'beed', 'bhandara', 'buldhana', 'chandrapur',
       'chhatrapati_sambhajinagar', 'dharashiv', 'dhule', 'gadchiroli',
       'gondia', 'hingoli', 'bishnupur', 'chandel', 'churachandpur',
       'imphal_east', 'imphal_west', 'senapati', 'tamenglong', 'thoubal',
       'ukhrul', '2013_2014', 'east_garo_hills', 'east_jaintia_hills',
       'east_khasi_hills', 'north_garo_hills', 'ri_bhoi',
       'south_garo_hills', 'south_west_garo_hills',
       'south_west_khasi_hills', 'west_garo_hills', 'west_jaintia_hills',
       'west_khasi_hills', 'aizawl', 'champhai', 'hnahthial', 'khawzawl',
       'kolasib', 'lawngtlai', 'lunglei', 'mamit', 'saiha', 'saitual',
       'serchhip', '2006_2007', 'chumoukedima', 'dimapur', 'kiphire',
       'kohima', 'longleng', 'mokokchung', 'mon', 'noklak', 'nuiland',
       'peren', 'phek', 'shamator', 'tseminyu', 'tuensang', 'wokha',
       'zunheboto', '1998_1999', '1999_2000', '2001_2002', '2002_2003',
       '2003_2004', '2005_2006', 'anugul', 'balangir', 'baleshwar',
       'bargarh', 'bhadrak', 'boudh', 'cuttack', 'deogarh', 'dhenkanal',
       'gajapati', 'ganjam', 'jagatsinghapur', 'jajapur', 'jharsuguda',
       'kalahandi', 'kandhamal', 'kendrapara', 'kendujhar', 'khordha',
       'koraput', 'malkangiri', 'mayurbhanj', 'nabarangpur', 'nayagarh',
       'nuapada', 'puri', 'rayagada', 'sambalpur', 'sonepur',
       'sundargarh', '2008_2009', '2012_2013', 'karaikal', 'mahe',
       'pondicherry', 'yanam', '2022_2023', 'amritsar', 'barnala',
       'bathinda', 'faridkot', 'fatehgarh_sahib', 'fazilka', 'firozepur',
       'gurdaspur', 'hoshiarpur', 'jalandhar', 'kapurthala', 'ludhiana',
       'malerkotla', 'mansa', 'moga', 'muktsar', 'nawanshahr', 'ajmer',
       'alwar', 'banswara', 'baran', 'barmer', 'bharatpur', 'bhilwara',
       'bikaner', 'bundi', 'chittorgarh', 'churu', 'gangtok', 'geyzing',
       'mangan', 'namchi', '1997_1998', 'ariyalur', 'chengalpattu',
       'chennai', 'coimbatore', 'cuddalore', 'dharmapuri', 'dindigul',
       'erode', 'kallakurichi', 'kanchipuram', 'kanniyakumari', 'karur',
       'krishnagiri', 'adilabad', 'karimnagar', 'khammam', 'mahbubnagar',
       'medak', 'nalgonda', 'nizamabad', 'rangareddi', 'warangal',
       'dhalai', 'gomati', 'khowai', 'north_tripura', 'sepahijala',
       'south_tripura', 'unakoti', 'west_tripura', 'agra', 'aligarh',
       'allahabad', 'ambedkar_nagar', 'amroha', 'auraiya', 'azamgarh',
       'baghpat', 'bahraich', 'ballia', 'banda', 'barabanki', 'bareilly',
       'basti', 'bijnor', 'budaun', 'bulandshahr', 'chandauli',
       'chitrakoot', 'deoria', 'etah', 'etawah', 'faizabad',
       'farrukhabad', 'fatehpur', 'almora', 'bageshwar', 'chamoli',
       'champawat', 'dehradun', 'haridwar', 'nainital', 'pauri_garhwal',
       'pithoragarh', 'rudra_prayag', 'tehri_garhwal', '2011_2012',
       '24_paraganas_north', '24_paraganas_south', 'alipurduar',
       'bankura', 'birbhum', 'coochbehar', 'darjeeling',
       'dinajpur_dakshin', 'dinajpur_uttar', 'hooghly', 'howrah'],
      dtype=object)

In [103]:
fertilizer_df = pd.read_csv('D:/Work/Coding/SIH 2025/agricultural-ai-platform/data/ML/fertilizer_crop.csv')
fertilizer_df['label'].unique()

array(['rice', 'maize', 'chickpea', 'kidneybeans', 'pigeonpeas',
       'mothbeans', 'mungbean', 'blackgram', 'lentil', 'pomegranate',
       'banana', 'mango', 'grapes', 'watermelon', 'muskmelon', 'apple',
       'orange', 'papaya', 'coconut', 'cotton', 'jute', 'coffee'],
      dtype=object)